services:
  - type: web
    name: coursewebmok
    env: node
    buildCommand: |
      chmod +x ./render-build.sh
      ./render-build.sh
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        fromDatabase:
          name: mongodb
          property: connectionString
    build:
      nodeVersion: 16.14.0
    staticPublishPath: "./frontend/build"
    routes:
      - type: rewrite
        source: /(.*)
        destination: /index.html

# Database configuration
databases:
  - name: mongodb
    databaseName: coursewebmok
    user: coursewebmok
